### ISSUE TITLE
User Story: Chat Interface

### ISSUE THREAD

**Issue by mbuturuga** [Dobbi-UDL/Dobbi#116]
### Description
As a user,
I want an intuitive chat interface
so that I can easily communicate with the AI financial advisor.

### Requirements
- User is logged in
- User is on the chat screen

### Acceptance Criteria
- [x] Text input field to send messages with a send button
- [x] Chat bubbles for messages
- [x] Sender and receiver images for chat bubbles

**Comment by mbuturuga** [comment]
[TIME TRACKING REQUIRED] Please document:
- Project start date
- Project completion date  
- Total hours spent on implementation
