### ISSUE TITLE
User Story: Chat History

### ISSUE THREAD

**Issue by mbuturuga** [Dobbi-UDL/Dobbi#118]
### Description
As a user, I want to start new chats and see older chats so that I can manage my conversations.

### Requirements
- User is logged in
- User is on the chat screen

### Acceptance Criteria
- [x] Button to access options for new chat or chat history
- [x] User can start a new chat
- [x] User can access previous chat history
- [x] A list of previous chats is displayed
- [x] Clicking on a chat opens that chat session

### Dependencies
- #117
