### ISSUE TITLE
Epic: Company Authentication

### ISSUE THREAD

**Issue by mbuturuga** [Dobbi-UDL/Dobbi#4]
### Description
This Epic involves all the features related to company authentication on the platform.

### Features
- [x] Dobbi-UDL/Dobbi-Project#68 
- [x] Dobbi-UDL/Dobbi-Project#23 
- [ ] Dobbi-UDL/Dobbi-Project#24 
- [ ] Dobbi-UDL/Dobbi-Project#25 
- [x] Dobbi-UDL/Dobbi-Project#26
