### ISSUE TITLE
Epic: User Authentication

### ISSUE THREAD

**Issue by mbuturuga** [Dobbi-UDL/Dobbi#44]
### Description
As a dev,
I want to implement basic user authentication
so that users can register, log in and log out.

### Features
- [x] Dobbi-UDL/Dobbi-Project#63 
- [x]  Dobbi-UDL/Dobbi-Project#64 
- [x] Dobbi-UDL/Dobbi-Project#65 
- [x] Dobbi-UDL/Dobbi-Project#66
